Fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -128,7 +128,7 @@ jobs:
           branch: main
           file_pattern: fastlane/metadata
           commit_message: Update Release Notes
-  buildWithLinux:
+  build:
     name: Build for ${{ matrix.targetPlatform }}
     runs-on:  ${{ matrix.runOn }}
     needs: tests
@@ -141,6 +141,8 @@ jobs:
           - StandaloneLinux64
           - WebGL
           - StandaloneOSX
+          - StandaloneWindows
+          - StandaloneWindows64
         include:
           - targetPlatform: Android
             runOn: ubuntu-latest
@@ -152,7 +154,10 @@ jobs:
             runOn: ubuntu-latest
           - targetPlatform: StandaloneOSX
             runOn: macos-latest
-
+          - targetPlatform: StandaloneWindows
+            runOn: windows-latest
+          - targetPlatform: StandaloneWindows64
+            runOn: windows-latest
     outputs:
       buildVersion: ${{ steps.build.outputs.buildVersion }}
     steps:
@@ -232,7 +237,7 @@ jobs:
   deployToGooglePlay:
     name: Deploy to the Google Play Store
     runs-on: ubuntu-latest
-    needs: buildWithLinux
+    needs: build
     if: github.event.action == 'published' || (contains(github.event.inputs.workflow_mode, 'release') && contains(github.event.inputs.workflow_mode, 'Android'))
     steps:
       - name: Checkout Repository
@@ -268,7 +273,7 @@ jobs:
   deployToGitHubPages:
     name: Deploy to the Web via GitHub Pages
     runs-on: ubuntu-latest
-    needs: buildWithLinux
+    needs: build
     if: github.event.action == 'published' || (contains(github.event.inputs.workflow_mode, 'release') && contains(github.event.inputs.workflow_mode, 'WebGL'))
     steps:
       - name: Checkout Repository
@@ -376,7 +381,7 @@ jobs:
   deployToMacAppStore:
     name: Deploy to the Mac App Store
     runs-on: macos-latest
-    needs: buildWithLinux
+    needs: build
     if: github.event.action == 'published' || (contains(github.event.inputs.workflow_mode, 'release') && contains(github.event.inputs.workflow_mode, 'StandaloneOSX'))
     steps:
       - name: Checkout Repository
@@ -409,7 +414,7 @@ jobs:
   deployToAppStore:
     name: Deploy to the App Store
     runs-on: macos-latest
-    needs: buildWithLinux
+    needs: build
     if: github.event.action == 'published' || (contains(github.event.inputs.workflow_mode, 'release') && contains(github.event.inputs.workflow_mode, 'iOS'))
     steps:
       - name: Checkout Repository
@@ -445,79 +450,79 @@ jobs:
           find $IOS_BUILD_PATH -type f -iname "usymtool" -exec chmod +x {} \;
           bundle install
           bundle exec fastlane ios release
-  buildWithWindows:
-    name: Build for ${{ matrix.targetPlatform }}
-    runs-on: windows-2019
-    needs: buildWithLinux 
-    outputs:
-      buildVersion: ${{ steps.build.outputs.buildVersion }}
-    strategy:
-      fail-fast: false
-      matrix:
-        targetPlatform:
-          - StandaloneWindows
-          - StandaloneWindows64
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Create LFS file list
-        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
-      - name: Restore LFS cache
-        uses: actions/cache@v3
-        id: lfs-cache
-        with:
-          path: .git/lfs
-          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
-      - name: Git LFS Pull
-        run: |
-          git lfs pull
-          git add .
-          git reset --hard
-      - uses: actions/cache@v3
-        with:
-          path: Library
-          key: Library-buildWindows-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
-          restore-keys: |
-            Library-buildWindows-${{ matrix.targetPlatform }}-
-            Library-buildWindows-
-      - name: Build Unity Project
-        id: build
-        uses: game-ci/unity-builder@v2.2.0
-        env:
-          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-        with:
-          targetPlatform: ${{ matrix.targetPlatform }}
-          buildMethod: Cgs.Editor.BuildCgs.BuildOptions
-      - name: Upload Build
-        uses: actions/upload-artifact@v3
-        if: github.event.action == 'published' || contains(github.event.inputs.workflow_mode, matrix.targetPlatform) || (contains(github.event.inputs.workflow_mode, 'Steam') && contains(matrix.targetPlatform, 'StandaloneWindows'))
-        with:
-          name: cgs-${{ matrix.targetPlatform }}
-          path: build/${{ matrix.targetPlatform }}
-      - name: Zip Build
-        uses: vimtor/action-zip@v1
-        if: github.event.action == 'published' && matrix.targetPlatform != 'WSAPlayer'
-        with:
-          files: build/${{ matrix.targetPlatform }}/
-          dest: build/cgs-${{ matrix.targetPlatform }}.zip
-      - name: Upload Zip to GitHub Release
-        uses: svenstaro/upload-release-action@v2
-        if: github.event.action == 'published' && matrix.targetPlatform != 'WSAPlayer'
-        with:
-          repo_token: ${{ secrets.CGS_PAT }}
-          asset_name: cgs-${{ matrix.targetPlatform }}.zip
-          file: build/cgs-${{ matrix.targetPlatform }}.zip
-          tag: ${{ github.ref }}
-          overwrite: true
-          body: ${{ github.event.release.body }}
+#  build:
+#    name: Build for ${{ matrix.targetPlatform }}
+#    runs-on: windows-2019
+#    needs: build 
+#    outputs:
+#      buildVersion: ${{ steps.build.outputs.buildVersion }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        targetPlatform:
+#          - StandaloneWindows
+#          - StandaloneWindows64
+#    steps:
+#      - name: Checkout Repository
+#        uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 0
+#      - name: Create LFS file list
+#        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+#      - name: Restore LFS cache
+#        uses: actions/cache@v3
+#        id: lfs-cache
+#        with:
+#          path: .git/lfs
+#          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+#      - name: Git LFS Pull
+#        run: |
+#          git lfs pull
+#          git add .
+#          git reset --hard
+#      - uses: actions/cache@v3
+#        with:
+#          path: Library
+#          key: Library-buildWindows-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
+#          restore-keys: |
+#            Library-buildWindows-${{ matrix.targetPlatform }}-
+#            Library-buildWindows-
+#      - name: Build Unity Project
+#        id: build
+#        uses: game-ci/unity-builder@v2.2.0
+#        env:
+#          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
+#          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+#          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
+#        with:
+#          targetPlatform: ${{ matrix.targetPlatform }}
+#          buildMethod: Cgs.Editor.BuildCgs.BuildOptions
+#      - name: Upload Build
+#        uses: actions/upload-artifact@v3
+#        if: github.event.action == 'published' || contains(github.event.inputs.workflow_mode, matrix.targetPlatform) || (contains(github.event.inputs.workflow_mode, 'Steam') && contains(matrix.targetPlatform, 'StandaloneWindows'))
+#        with:
+#          name: cgs-${{ matrix.targetPlatform }}
+#          path: build/${{ matrix.targetPlatform }}
+#      - name: Zip Build
+#        uses: vimtor/action-zip@v1
+#        if: github.event.action == 'published' && matrix.targetPlatform != 'WSAPlayer'
+#        with:
+#          files: build/${{ matrix.targetPlatform }}/
+#          dest: build/cgs-${{ matrix.targetPlatform }}.zip
+#      - name: Upload Zip to GitHub Release
+#        uses: svenstaro/upload-release-action@v2
+#        if: github.event.action == 'published' && matrix.targetPlatform != 'WSAPlayer'
+#        with:
+#          repo_token: ${{ secrets.CGS_PAT }}
+#          asset_name: cgs-${{ matrix.targetPlatform }}.zip
+#          file: build/cgs-${{ matrix.targetPlatform }}.zip
+#          tag: ${{ github.ref }}
+#          overwrite: true
+#          body: ${{ github.event.release.body }}
   deployToMicrosoftStore:
     name: Deploy to the Microsoft Store
     runs-on: windows-2019
-    needs: buildWithWindows
+    needs: build
     if: github.event.action == 'published' || (contains(github.event.inputs.workflow_mode, 'release') && contains(github.event.inputs.workflow_mode, 'WSAPlayer'))
     steps:
       - name: Checkout Repository
@@ -641,8 +646,8 @@ jobs:
       - name: Upload .appxupload
         uses: actions/upload-artifact@v3
         with:
-          name: ${{ format('CardGameSimulator_{0}.0_x64_bundle_Master.appxupload', needs.buildWithWindows.outputs.buildVersion) }}
-          path: ${{ format('{0}\build\WSAPlayer\WSAPlayer\AppPackages\CardGameSimulator\CardGameSimulator_{1}.0_x64_bundle_Master.appxupload', 'C:\Card-Game-Simulator.git', needs.buildWithWindows.outputs.buildVersion) }}
+          name: ${{ format('CardGameSimulator_{0}.0_x64_bundle_Master.appxupload', needs.build.outputs.buildVersion) }}
+          path: ${{ format('{0}\build\WSAPlayer\WSAPlayer\AppPackages\CardGameSimulator\CardGameSimulator_{1}.0_x64_bundle_Master.appxupload', 'C:\Card-Game-Simulator.git', needs.build.outputs.buildVersion) }}
       - name: Upload to the Microsoft Store
         working-directory: C:/Card-Game-Simulator.git
         shell: pwsh
@@ -654,7 +659,7 @@ jobs:
           STOREBROKER_CONFIG_PATH: ${{ format('{0}\storebroker\SBConfig.json', 'C:\Card-Game-Simulator.git') }}
           PDP_ROOT_PATH: ${{ format('{0}\storebroker\', 'C:\Card-Game-Simulator.git') }}
           IMAGES_ROOT_PATH: ${{ format('{0}\docs\assets\img\', 'C:\Card-Game-Simulator.git') }}
-          APPX_PATH: ${{ format('{0}\build\WSAPlayer\WSAPlayer\AppPackages\CardGameSimulator\CardGameSimulator_{1}.0_x64_bundle_Master.appxupload', 'C:\Card-Game-Simulator.git', needs.buildWithWindows.outputs.buildVersion) }}
+          APPX_PATH: ${{ format('{0}\build\WSAPlayer\WSAPlayer\AppPackages\CardGameSimulator\CardGameSimulator_{1}.0_x64_bundle_Master.appxupload', 'C:\Card-Game-Simulator.git', needs.build.outputs.buildVersion) }}
           OUT_PATH: ${{ format('{0}\build\WSAPlayer\WSAPlayer\', 'C:\Card-Game-Simulator.git') }}
           SUBMISSION_DATA_PATH: ${{ format('{0}\build\WSAPlayer\WSAPlayer\upload.json', 'C:\Card-Game-Simulator.git') }}
           PACKAGE_PATH: ${{ format('{0}\build\WSAPlayer\WSAPlayer\upload.zip', 'C:\Card-Game-Simulator.git') }}
@@ -669,7 +674,7 @@ jobs:
   deployToSteam:
     name: Deploy to the Steam Marketplace
     runs-on: ubuntu-latest
-    needs: buildWithWindows
+    needs: build
     if: github.event.action == 'published' || (contains(github.event.inputs.workflow_mode, 'release') && contains(github.event.inputs.workflow_mode, 'Steam'))
     steps:
       - name: Checkout Repository
@@ -703,7 +708,7 @@ jobs:
           ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
           ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
           appId: 1742850
-          buildDescription: v${{ needs.buildWithWindows.outputs.buildVersion }}
+          buildDescription: v${{ needs.build.outputs.buildVersion }}
           rootPath: build
           depot1Path: StandaloneWindows
           depot2Path: StandaloneLinux64
@@ -713,7 +718,7 @@ jobs:
   announceReleaseToSocialMedia:
     name: Announce Release to Social Media
     runs-on: ubuntu-latest
-    needs: [ buildWithWindows, deployToAppStore, deployToGooglePlay, deployToGitHubPages, deployToMacAppStore, deployToMicrosoftStore, deployToSteam ]
+    needs: [ build, deployToAppStore, deployToGooglePlay, deployToGitHubPages, deployToMacAppStore, deployToMicrosoftStore, deployToSteam ]
     if: github.event.action == 'published'
     steps:
       - name: Checkout Repository
@@ -722,7 +727,7 @@ jobs:
         id: prepare
         shell: bash
         env:
-          VERSION: v${{ needs.buildWithWindows.outputs.buildVersion }}
+          VERSION: v${{ needs.build.outputs.buildVersion }}
           RELEASE_NOTES: ${{ github.event.release.body }}
         run: |
           export ANNOUNCEMENT="Released CGS $VERSION! $RELEASE_NOTES"
